const description = [
    'Is a simple settlement where common housing is constructed out of clay for walls and thatch for the ceiling. The streets muddy and smell of a variety of faeces mixed with rotten food and carcasses.  Many of the people here are humble farmers, lumberjacks, and fishers as well as otherrolls necessary for the settlement to survive',
    'This settlement screams wealthy, anyone important strives to come here for a break as it is the current must be destination.  This settlement is recently completed as an entertainment city for the wealthy.  All forms of entertainment can be found here ranging from family friendly to more adult content later at night.  Rumour has it that the headquarters of one of the countries most powerful crime syndicate dwells here.',
    'A sparse and famous wine district where many of its brands are known and imported on an international scale.  Due to this wealth manors and mansions are intertwined with distilleries.  The secret to its success is rumours of mistreatment of an underclass labour force.',
    'An ancient city that has existed since the dawn of the time which has survived countless wars, invasions and changes of government.  The people are as hardy as its walls.',
    'A peaceful seaside settlement which whose officials act as ambassadors for the kingdom to neighbouring sea-dwelling kingdoms.  However, there are radicalson both sides who wish to end the stable peace treaty.',
    'This settlement is home to an ancient monastic order which protects the settlement from any and all outside dangers.  Resulting, in a strong and prideful spirit of independence and refuse to become a vassal province under any ruler, group or organisation.',
    'The settlement is its people and the people are the settlement.  A nomadic caravan which moves between regions to sell their wares, and trade stories. The other settlements need their wares but caravan is always distrusted and only a limited number are allowed inside any settlement at any one time. (For this to make sense recommend limit population to a maximum of 400).',
    'A vast underground mining settlement.  Approximately 90% of the population are minors with a handful of surface buildings which act as warehouses and tradestores for the town to negotiate bulk orders of its wares.  Main product is iron, steel, and some precious gems.  All races in this settlement have developed a echolocation and a type of heatvision to see better in the dark.',
    'A settlement in the clouds, through archeotech are able to use the clouds to grow their crops.  Their surroundings are crafted out of solidified cloud due to specialised archeotech and or magical beasts.  Believe themselves to be above everyone else and have never come into contact with any outsiders.',
    'A settlement in the treetops of a great forest, whose ground consists of many a dangerous monster and predator.  Rely on fairies for their light and messengers in case a scouting or hunting party falls to intruders. Have peace treaties with various fay tribes and are guardians to any portal which leads to a sylvan or emotionally driven plane.',
];

module.exports = description;
